p8105\_hw5\_rr3423.Rmd
================
Ragyie Rawal

## PROBLEM 1

``` r
homicide_data = read_csv("data/homicide-data.csv", na = c("", "Unknown"))
```

    ## Rows: 52179 Columns: 12

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (8): uid, victim_last, victim_first, victim_race, victim_sex, city, stat...
    ## dbl (4): reported_date, victim_age, lat, lon

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

### Describing raw data

``` r
homicide_variable = 
  homicide_data %>% 
  names()

homicide_columns = 
  homicide_data %>% 
  ncol()

homicide_rows = 
  homicide_data %>% 
  nrow()
```

The **key variables** in the raw homicide dataset are uid,
reported\_date, victim\_last, victim\_first, victim\_race, victim\_age,
victim\_sex, city, state, lat, lon, disposition. The **number of
columns** in the raw homicide dataset are 12. The **number of rows** in
the raw homicide dataset are 52179. There is data provided for a total
of **52179 homicides** from 50 large U.S. cities. The raw dataset
contained “Unknown” and blank data values, which I replaced with “NA”
values when importing the csv file.

### Creating city-state and resolution variables

``` r
homicide_df = 
  homicide_data %>%
  mutate(
    city_state = str_c(city, state),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved"
    )) %>% 
  relocate(city_state) %>% 
  filter(city_state != "TulsaAL")
```

### Summary of the total number of homicides and the number of unsolved homicides within cities

``` r
# summarizing total number of homicides within cities 
homicide_df %>% 
  count(city_state) %>% 
  knitr::kable(
    caption = "**Table 1: Total number of homicides within cities**"
  )
```

| city\_state      |    n |
|:-----------------|-----:|
| AlbuquerqueNM    |  378 |
| AtlantaGA        |  973 |
| BaltimoreMD      | 2827 |
| Baton RougeLA    |  424 |
| BirminghamAL     |  800 |
| BostonMA         |  614 |
| BuffaloNY        |  521 |
| CharlotteNC      |  687 |
| ChicagoIL        | 5535 |
| CincinnatiOH     |  694 |
| ColumbusOH       | 1084 |
| DallasTX         | 1567 |
| DenverCO         |  312 |
| DetroitMI        | 2519 |
| DurhamNC         |  276 |
| Fort WorthTX     |  549 |
| FresnoCA         |  487 |
| HoustonTX        | 2942 |
| IndianapolisIN   | 1322 |
| JacksonvilleFL   | 1168 |
| Kansas CityMO    | 1190 |
| Las VegasNV      | 1381 |
| Long BeachCA     |  378 |
| Los AngelesCA    | 2257 |
| LouisvilleKY     |  576 |
| MemphisTN        | 1514 |
| MiamiFL          |  744 |
| MilwaukeewI      | 1115 |
| MinneapolisMN    |  366 |
| NashvilleTN      |  767 |
| New OrleansLA    | 1434 |
| New YorkNY       |  627 |
| OaklandCA        |  947 |
| Oklahoma CityOK  |  672 |
| OmahaNE          |  409 |
| PhiladelphiaPA   | 3037 |
| PhoenixAZ        |  914 |
| PittsburghPA     |  631 |
| RichmondVA       |  429 |
| SacramentoCA     |  376 |
| San AntonioTX    |  833 |
| San BernardinoCA |  275 |
| San DiegoCA      |  461 |
| San FranciscoCA  |  663 |
| SavannahGA       |  246 |
| St. LouisMO      | 1677 |
| StocktonCA       |  444 |
| TampaFL          |  208 |
| TulsaOK          |  583 |
| WashingtonDC     | 1345 |

**Table 1: Total number of homicides within cities**

``` r
# summarizing total number of unsolved homicides within cities 
homicide_df %>% 
  filter(resolution == "unsolved") %>% 
  group_by(city_state, resolution) %>% 
  summarize(n = n()) %>% 
  knitr::kable(
    caption = "**Table 2: Total number of unsolved homicides within cities**"
  )
```

| city\_state      | resolution |    n |
|:-----------------|:-----------|-----:|
| AlbuquerqueNM    | unsolved   |  146 |
| AtlantaGA        | unsolved   |  373 |
| BaltimoreMD      | unsolved   | 1825 |
| Baton RougeLA    | unsolved   |  196 |
| BirminghamAL     | unsolved   |  347 |
| BostonMA         | unsolved   |  310 |
| BuffaloNY        | unsolved   |  319 |
| CharlotteNC      | unsolved   |  206 |
| ChicagoIL        | unsolved   | 4073 |
| CincinnatiOH     | unsolved   |  309 |
| ColumbusOH       | unsolved   |  575 |
| DallasTX         | unsolved   |  754 |
| DenverCO         | unsolved   |  169 |
| DetroitMI        | unsolved   | 1482 |
| DurhamNC         | unsolved   |  101 |
| Fort WorthTX     | unsolved   |  255 |
| FresnoCA         | unsolved   |  169 |
| HoustonTX        | unsolved   | 1493 |
| IndianapolisIN   | unsolved   |  594 |
| JacksonvilleFL   | unsolved   |  597 |
| Kansas CityMO    | unsolved   |  486 |
| Las VegasNV      | unsolved   |  572 |
| Long BeachCA     | unsolved   |  156 |
| Los AngelesCA    | unsolved   | 1106 |
| LouisvilleKY     | unsolved   |  261 |
| MemphisTN        | unsolved   |  483 |
| MiamiFL          | unsolved   |  450 |
| MilwaukeewI      | unsolved   |  403 |
| MinneapolisMN    | unsolved   |  187 |
| NashvilleTN      | unsolved   |  278 |
| New OrleansLA    | unsolved   |  930 |
| New YorkNY       | unsolved   |  243 |
| OaklandCA        | unsolved   |  508 |
| Oklahoma CityOK  | unsolved   |  326 |
| OmahaNE          | unsolved   |  169 |
| PhiladelphiaPA   | unsolved   | 1360 |
| PhoenixAZ        | unsolved   |  504 |
| PittsburghPA     | unsolved   |  337 |
| RichmondVA       | unsolved   |  113 |
| SacramentoCA     | unsolved   |  139 |
| San AntonioTX    | unsolved   |  357 |
| San BernardinoCA | unsolved   |  170 |
| San DiegoCA      | unsolved   |  175 |
| San FranciscoCA  | unsolved   |  336 |
| SavannahGA       | unsolved   |  115 |
| St. LouisMO      | unsolved   |  905 |
| StocktonCA       | unsolved   |  266 |
| TampaFL          | unsolved   |   95 |
| TulsaOK          | unsolved   |  193 |
| WashingtonDC     | unsolved   |  589 |

**Table 2: Total number of unsolved homicides within cities**

### Focusing on Baltimore, MD

``` r
baltimore_df = 
  homicide_df %>% 
  filter(city_state == "BaltimoreMD")

baltimore_summary = 
  baltimore_df %>% 
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  )

# prop.test to estimate proportion of unsolved homicides in baltimore 
baltimore_test = 
  prop.test(
  x = baltimore_summary %>% pull(unsolved),
  n = baltimore_summary %>% pull(n)
)

# applying broom::tidy
baltimore_test %>% 
  broom::tidy()
```

    ## # A tibble: 1 × 8
    ##   estimate statistic  p.value parameter conf.low conf.high method    alternative
    ##      <dbl>     <dbl>    <dbl>     <int>    <dbl>     <dbl> <chr>     <chr>      
    ## 1    0.646      239. 6.46e-54         1    0.628     0.663 1-sample… two.sided

From the resulting tidy dataframe, the estimated proportion is 0.646 and
the 95% confidence interval is (0.628, 0.663). This means that
approximately 64.6% of homicides in Baltimore are unsolved.

### Creating prop.test function

``` r
# creating a function 
prop_test_function = function(city_df) {
  
  city_summary = 
    city_df %>% 
    summarize(
      unsolved = sum(resolution == "unsolved"),
      n = n()
    )

  city_test = 
   prop.test(
    x = city_summary %>% pull(unsolved),
    n = city_summary %>% pull(n)
  )
  
  return(city_test)
  
}

# testing function on some cities
prop_test_function(baltimore_df)
```

    ## 
    ##  1-sample proportions test with continuity correction
    ## 
    ## data:  city_summary %>% pull(unsolved) out of city_summary %>% pull(n), null probability 0.5
    ## X-squared = 239.01, df = 1, p-value < 2.2e-16
    ## alternative hypothesis: true p is not equal to 0.5
    ## 95 percent confidence interval:
    ##  0.6275625 0.6631599
    ## sample estimates:
    ##         p 
    ## 0.6455607

``` r
homicide_df %>% 
  filter(city_state == "AlbuquerqueNM") %>% 
  prop_test_function
```

    ## 
    ##  1-sample proportions test with continuity correction
    ## 
    ## data:  city_summary %>% pull(unsolved) out of city_summary %>% pull(n), null probability 0.5
    ## X-squared = 19.114, df = 1, p-value = 1.232e-05
    ## alternative hypothesis: true p is not equal to 0.5
    ## 95 percent confidence interval:
    ##  0.3372604 0.4375766
    ## sample estimates:
    ##         p 
    ## 0.3862434

# Iterating across cities

``` r
# nesting dataset within cities 
nested_df = 
  homicide_df %>% 
  nest(data = uid:resolution)
```
